apiVersion: v1
kind: Service
metadata:
  name: mern-backend
  namespace: mern
  labels:
    app.kubernetes.io/name: mern-backend
    app.kubernetes.io/part-of: mern-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mern-backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
