apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
  namespace: mern
  labels:
    app.kubernetes.io/name: mern-frontend
    app.kubernetes.io/part-of: mern-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mern-frontend
  ports:
    - port: 80
      targetPort: 4200
      protocol: TCP
      name: http
