apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mongodb-secret.yaml
  - mongodb-service.yaml
  - mongodb-statefulset.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: mern-stack
namespace: mern
