apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: mern
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: mern
type: Opaque
stringData:
  mongodb-username: mernuser
  mongodb-password: S3cure
  mongodb-database: mern
  mongodb-uri: mongodb://mernuser:S3cure@mongodb-headless.mern.svc.cluster.local:27017/mern?authSource=admin
  mongodb-root-password: S3cure
