apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-mongodb-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/mongodb-0
    type: DirectoryOrCreate
  claimRef:
    namespace: mern
    name: data-mongodb-0
